### ISSUE TITLE
should it include "alfg/" if run from docker image?

### ISSUE THREAD

**Issue by qiaoyan** [alfg/docker-nginx-rtmp#1]
docker pull alfg/nginx-rtmp
docker run -it -p 1935:1935 -p 8080:80 --rm alfg/nginx-rtmp

**Comment by alfg** [comment]
Hi @qiaoyan,

Yes, that should be right. Is there a problem when running?

**Comment by alfg** [comment]
Ah, I just noticed the typo and fixed.
https://github.com/alfg/docker-nginx-rtmp/commit/9787104c9d7d4ed5720ce1687f48a78a45012a24

When running, it should be:
```
docker run -it -p 1935:1935 -p 8080:80 --rm alfg/nginx-rtmp
```
