### ISSUE TITLE
Improve the image size using docker multi-stage builds

### ISSUE THREAD

**Issue by Gary-Ascuy** [alfg/docker-nginx-rtmp#10]
https://docs.docker.com/develop/develop-images/multistage-build/#before-multi-stage-builds

**Comment by alfg** [comment]
I like this idea, do you have an example that i can use?

**Comment by Gary-Ascuy** [comment]
for this particular use case no, but in general: you can install dev dependencies into first image and use this as builder and copy the artifact to other image, with this we can keep clean of dev dependencies the second image 

**Dockerfile with 2 phases**
```
# first stage it is just to create the artifact (binary)
FROM golang:1.7.3
WORKDIR /go/src/github.com/alexellis/href-counter/
RUN go get -d -v golang.org/x/net/html  
COPY app.go .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .

# Use alpine as base and adds the artifact from first stage
FROM alpine:latest  
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=0 /go/src/github.com/alexellis/href-counter/app . # copy artifacts from first stage
CMD ["./app"]  
```

**Comment by Gary-Ascuy** [comment]
so the hard work I think it is identify real dependencies from all dependencies in order to remove from the final image

**Comment by alfg** [comment]
#7

**Comment by alfg** [comment]
Added with #13
