### ISSUE TITLE
Switch to sergey-dryabzhinsky/nginx-rtmp-module?

### ISSUE THREAD

**Issue by rmens** [alfg/docker-nginx-rtmp#100]
There is a fork of the original nginx-rtmp-module that is a lot more active with bug fixes. Is it maybe a good idea to switch to that version? https://github.com/sergey-dryabzhinsky/nginx-rtmp-module

**Comment by alfg** [comment]
Hi @rmens. Thanks for the suggestion. I like the idea of using a forked project that is actively maintained. However, I want to keep the `latest` tag on this project true to the original `nginx-rtmp-module` source.

I'm open to PRs using a separate Dockerfile from a maintained fork, though. Similar to the Cuda build and registering it as a separate tag.
