### ISSUE TITLE
Problem running the docker image..

### ISSUE THREAD

**Issue by PAOK1926** [alfg/docker-nginx-rtmp#106]
hello, 

in a clean alpine container under proxmox, i'm trying to run your image..
but the execution stops here:

![Screenshot 2022-02-17 at 14 55 35](https://user-images.githubusercontent.com/31358094/154486098-8114a0cf-5218-4bb3-b166-7ab0fc897a78.png)

**Comment by alfg** [comment]
I've seen these warnings before, but I believe the container should still be running and functional. Are you able to load and stream?

**Comment by alfg** [comment]
Closing. Feel free to respond with the question above. Thanks!
