### ISSUE TITLE
Possible to add curl to the container?

### ISSUE THREAD

**Issue by reedog117** [alfg/docker-nginx-rtmp#11]
I'm trying to implement auto-switching between different feeds but this requires curl to be in the container, which it's not by default. Any chance that this can be added?

**Comment by alfg** [comment]
Hi @reedog117, 

I don't mind adding it in, but do you have an example on how you are using curl for auto-switching feeds?

**Comment by reedog117** [comment]
See this thread for a good example of using curl for auto-switching feeds.

https://groups.google.com/forum/#!topic/nginx-rtmp/qKsJNWiRACo

**Comment by alfg** [comment]
Thanks @reedog117, 

That's a good example. I've added `curl` and updated the docker image.

Thanks!
