### ISSUE TITLE
How to use with reverse proxy?

### ISSUE THREAD

**Issue by Aerya** [alfg/docker-nginx-rtmp#132]
Hi,

Everything works out of the box using:
 - to stream: rtmp://10.0.4.7:1935/stream
 - to play: rtmp://10.0.4.7:1935/stream/key

I tried to use Nginx Reverse Proxy (Docker/jc21) to reverse 10.0.4.7:1935 to stream.domain.tld but I can't neither stream nor play.
I tried with/without SSL.

Any advice please?

**Comment by alfg** [comment]
I have not tried this setup, but I would suggest checking on the author's repo at https://github.com/arut/nginx-rtmp-module if there's any answers there.
