### ISSUE TITLE
unknown directive "more_set_headers"

### ISSUE THREAD

**Issue by xabikip** [alfg/docker-nginx-rtmp#134]
Hi,

I cloned this repo and execute `docker-compose up -d` but i have the following error:

`nginx: [emerg] unknown directive "more_set_headers" in /etc/nginx/nginx.conf:10`

Any idea that what can be happened?

Thanks for your work!

**Comment by alfg** [comment]
Not sure. I'm not getting this error when I do a fresh build. Are you using a custom nginx.conf?

**Comment by xabikip** [comment]
Sorry, it was my mistake. I had the directive "more_set_headers" in my nginx.conf and it escaped me. I removed and work perfectly.

**Comment by alfg** [comment]
No worries! Glad you got it figured out!
