### ISSUE TITLE
ffmpeg编译报错

### ISSUE THREAD

**Issue by bywei** [alfg/docker-nginx-rtmp#14]
编译的时候提示：
./configure: line 1: pr: not found

libavdevice/avdevice.c: In function 'device_next':
libavdevice/avdevice.c:88:13: warning: 'av_oformat_next' is deprecated [-Wdeprecated-declarations]
             if (!(prev = av_oformat_next(prev)))
             ^~
In file included from libavdevice/avdevice.h:51:0,
                 from libavdevice/avdevice.c:23:
./libavformat/avformat.h:2088:17: note: declared here
 AVOutputFormat *av_oformat_next(const AVOutputFormat *f);
                 ^~~~~~~~~~~~~~~
libavdevice/avdevice.c:92:13: warning: 'av_iformat_next' is deprecated [-Wdeprecated-declarations]
             if (!(prev = av_iformat_next(prev)))
             ^~
In file included from libavdevice/avdevice.h:51:0,
                 from libavdevice/avdevice.c:23:
./libavformat/avformat.h:2080:17: note: declared here
 AVInputFormat  *av_iformat_next(const AVInputFormat  *f);
                 ^~~~~~~~~~~~~~~

**Comment by alfg** [comment]
Hi @bywei, 

Are you referring to the compile warnings? I tried re-compiling and it works. There's usually a lot of warnings, but shouldn't affect the code.
