### ISSUE TITLE
404 not found/no such file or directory error

### ISSUE THREAD

**Issue by netstrem** [alfg/docker-nginx-rtmp#142]
hi. I've installed docker-nginx-rtmp and gotten ffmpeg to restream using:

```
docker run -it -p 1935:1935 -p 8080:80 --rm alfg/nginx-rtmp
```

```
ffmpeg -fflags +igndts -hide_banner -i {streamlink} -c copy -f flv rtmp://localhost:1935/stream/teststream
```

however if i try to access http://localhost:8080/live/teststream.m3u8 i result in a 404 not found error.

in the log from the shell from docker-nginx-rtmp, it says:

```
 [error] 11#11: *17 open() "/opt/data/hls/teststream.m3u8" failed (2: No such file or directory)
```

would you know how to resolve this issue? thanks for your help.

**Comment by rmens** [comment]
Can you look at http://localhost:8080/stat to see if there are streams? It should list one main stream and several hls streams like this

<img width="352" alt="Schermafbeelding 2022-09-21 om 12 21 22" src="https://user-images.githubusercontent.com/6742496/191480380-f29f138d-9483-417f-9058-037b2bb86ba8.png">

**Comment by netstrem** [comment]
it does have 1 main stream and hls streams for different stream qualities like you said
![image](https://user-images.githubusercontent.com/102488252/191613337-72d6359e-1b02-452d-b0fb-fe16f7eea0fe.png)

is there something that i have to edit?

**Comment by Richarn290** [comment]
> it does have 1 main stream and hls streams for different stream qualities like you said ![image](https://user-images.githubusercontent.com/102488252/191613337-72d6359e-1b02-452d-b0fb-fe16f7eea0fe.png)
> 
> is there something that i have to edit?

Do you know how to solve this problem in the end?Thank you

**Comment by 1md3nd** [comment]
I having the same issue, but there is no hls stream.

![Image](https://github.com/user-attachments/assets/7b40dd0d-523a-4645-a7f0-5e85b5b0c7ed)
