### ISSUE TITLE
the "ssl" parameter requires ngx_http_ssl_module

### ISSUE THREAD

**Issue by speekadievs** [alfg/docker-nginx-rtmp#15]
Would it be possible to add this module, so we could have ssl support?

**Comment by alfg** [comment]
Hey @speekadievs, 

I just added a PR https://github.com/alfg/docker-nginx-rtmp/pull/16/files. Please take a look over and see if this works for you and I'll merge it in.

**Comment by alfg** [comment]
Added via #16
