### ISSUE TITLE
Doesn't compile

### ISSUE THREAD

**Issue by guylevin** [alfg/docker-nginx-rtmp#17]
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g   -I src/core -I src/event -I src/event/modules -I src/os/unix -I /tmp/nginx-rtmp-module-1.2.1 -I objs -I src/http -I src/http/modules \
        -o objs/addon/nginx-rtmp-module-1.2.1/ngx_rtmp_shared.o \
        /tmp/nginx-rtmp-module-1.2.1/ngx_rtmp_shared.c
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g   -I src/core -I src/event -I src/event/modules -I src/os/unix -I /tmp/nginx-rtmp-module-1.2.1 -I objs -I src/http -I src/http/modules \
        -o objs/addon/nginx-rtmp-module-1.2.1/ngx_rtmp_eval.o \
        /tmp/nginx-rtmp-module-1.2.1/ngx_rtmp_eval.c
/tmp/nginx-rtmp-module-1.2.1/ngx_rtmp_eval.c: In function 'ngx_rtmp_eval':
/tmp/nginx-rtmp-module-1.2.1/ngx_rtmp_eval.c:160:17: error: this statement may fall through [-Werror=implicit-fallthrough=]
                 switch (c) {
                 ^~~~~~
/tmp/nginx-rtmp-module-1.2.1/ngx_rtmp_eval.c:170:13: note: here
             case ESCAPE:
             ^~~~
cc1: all warnings being treated as errors
make[1]: *** [objs/Makefile:1377: objs/addon/nginx-rtmp-module-1.2.1/ngx_rtmp_eval.o] Error 1
make[1]: Leaving directory '/tmp/nginx-1.14.2'
make: *** [Makefile:8: build] Error 2
The command '/bin/sh -c cd /tmp/nginx-${NGINX_VERSION} &&   ./configure   --prefix=/opt/nginx   --add-module=/tmp/nginx-rtmp-module-${NGINX_RTMP_VERSION}   --conf-path=/opt/nginx/nginx.conf   --with-threads   --with-file-aio   --with-http_ssl_module   --error-log-path=/opt/nginx/logs/error.log   --http-log-path=/opt/nginx/logs/access.log   --with-debug &&   cd /tmp/nginx-${NGINX_VERSION} && make && make install' returned a non-zero code: 2

**Comment by alfg** [comment]
Hi @guylevin, 

This might be due to the recent release of [Alpine 3.9](https://alpinelinux.org/posts/Alpine-3.9.0-released.html). Not sure exactly why it's breaking yet, but I updated to use Alpine 3.8 and it seems to compile again.

https://github.com/alfg/docker-nginx-rtmp/commit/76926c698c6a975ef2994e0b57a1084952f96511

Can you pull latest and try again?
