### ISSUE TITLE
docker exec /bin/bash or logs error

### ISSUE THREAD

**Issue by AKcheng** [alfg/docker-nginx-rtmp#18]
1. command enter docker output the following error
OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown

can only use /bin/sh enter docker
2.Through docker view log is empty, enter the container content view has log

**Comment by alfg** [comment]
Are you trying to shell in with bash? Alpine images don't have bash installed by default, just `sh`.
