### ISSUE TITLE
Can't connect with OBS

### ISSUE THREAD

**Issue by homanp** [alfg/docker-nginx-rtmp#2]
Hi @alfg, 

I'm running your docker image with digitalocean and everything seems to be working on the server  except for OBS telling me I can't connect to Stream. 

Very strange.

Do you have any idea why?

Thanks!

**Comment by alfg** [comment]
Hi @homanp, 

Does it connect if you run the docker image locally?

Also which Digital Ocean image are you using as your host? I wonder if you need to open the port (1935) in order to connect via OBS.

**Comment by homanp** [comment]
Hi there,

I’m using the docker dricker and all ports should be open by default. Runs locally but not on the server. 

Really strange, any other ideas?

Thanks

**Comment by homanp** [comment]
Docker droplet* that runs Ubuntu 16.04.

**Comment by alfg** [comment]
Can you post the command you are using to run the container? Are you able to access the stats page? `http://{host}/stat`.

Also, just making sure OBS is set up correctly to use the URL and stream key:
https://github.com/alfg/docker-nginx-rtmp#obs-configuration

**Comment by homanp** [comment]
I’m running:

docker pull alfg/nginx-rtmp
docker run -it -p 1935:1935 -p 8080:80 --rm alfg/nginx-rtmp

Yeah I can access the /stat

**Comment by alfg** [comment]
Hi @homanp, 

I just spun up a digitalocean droplet using the Docker image and everything seemed to be functional. 

Are you inputting the correct OBS connection settings?

```
Stream Type: Custom Streaming Server
URL: rtmp://{host}:1935/stream
Stream Key: hello
```

**Comment by homanp** [comment]
Which droplet did you use? The one-click install Docker?

I verified the Stream url a bunch of times. I’ll try it again today to check.

**Comment by alfg** [comment]
Yeah, the one-click docker install.

**Comment by homanp** [comment]
Ok, so you only did this:

docker pull alfg/nginx-rtmp
docker run -it -p 1935:1935 -p 8080:80 --rm alfg/nginx-rtmp

No other configuration on the droplet?

Thanks

**Comment by alfg** [comment]
Yeah, that is correct. And I connected to:

rtmp://{ip_address}:1935/stream
key: `hello`

And I see the data populated on the /stats page as well as the HLS stream on:
`http://{ip_address}:8080/live/hello.m3u8`

**Comment by homanp** [comment]
Ok cool! And on the OBS you just input the address and click “Start Stream”? 

Thanks again!

**Comment by alfg** [comment]
Yup, that is right. No other configuration or anything. 

I'm not sure why else it would be blocked. :\

**Comment by homanp** [comment]
Yeah, I’ll check again today and get back to you. Thanks for your help!

**Comment by homanp** [comment]
@alfg could you try to stream to `rtmp://146.185.149.221:1935/stream` I just setup up a new docker droplet. You can view the stats here `http://146.185.149.221:8080/stat`. 

Does it work for you?

**Comment by homanp** [comment]
@alfg works fine now! Thanks for all the help. Closing this.

Great work again!

**Comment by alfg** [comment]
Hey, sorry for the late response. I'm glad you got it working! 👍 

Also, I tried connecting to your stats page and stream and it worked. :)

**Comment by homanp** [comment]
Thanks again @alfg!
