### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by ReInventTheWheel** [alfg/docker-nginx-rtmp#20]
Step 25/32 : COPY --from=build-ffmpeg /usr/local /usr/local
 ---> 7cd5d23b3475
Step 26/32 : COPY --from=build-ffmpeg /usr/lib/libfdk-aac.so.1 /usr/lib/libfdk-aac.so.1
COPY failed: stat `/var/lib/docker/overlay2/aa04baefbdf0f2eba0e13995fad41dd2596c862884026f87084aa3076e9e7c2b/merged/usr/lib/libfdk-aac.so.1: no such file or directory`

**Comment by alexholliz** [comment]
I'm in the same boat, noticed there was an update for the libfdk-aac module, which cause the build to fail at first: https://github.com/mstorsjo/fdk-aac/issues/93

Then I found the updated dockerfile, so I incorporated those changes and now I get the same error as above.

**Comment by alexholliz** [comment]
I solved this, LibFDK-aac has been updated: https://www.archlinux.org/packages/community/x86_64/libfdk-aac/files/ (that's arch, but you can see the contents)

Change the copy step to copy libfdk-aac.so.2 

I'm able to build again.

**Comment by alexholliz** [comment]
I put in a PR to fix this: https://github.com/alfg/docker-nginx-rtmp/pull/21

**Comment by alfg** [comment]
Thanks for reporting this @ReInventTheWheel and for the fix @alexholliz!
