### ISSUE TITLE
Stunnel

### ISSUE THREAD

**Issue by aprisniak** [alfg/docker-nginx-rtmp#25]
Hi, 

Is there some plans to add stunnel support?
If I understood right this module is needed to migrate facebook stream from rtmp to rtmps.

Thx.

**Comment by alfg** [comment]
Hi @aprisniak, 

I haven't considered this before. Is this only when using the project as a relay?

I see some methods mentioned including stunnel (as you mentioned) in the nginx-rtmp-module issue tracker:
https://github.com/arut/nginx-rtmp-module/issues/1397

I will check into this.

**Comment by aprisniak** [comment]
Hi @alfg,

Yes, you are right. I will use your project as a relay. 
I will use it to stream to youtube and facebook. 

And I also saw this arut/nginx-rtmp-module#1397 issue.

**Comment by ispyisail** [comment]
I had problems like many other people

My problem was I was using the same Ports for Nginx and stunnel when on the same machine

I made this how-to

https://sites.google.com/view/facebook-rtmp-to-rtmps/home

**Comment by alfg** [comment]
Hi @ispyisail, 

Sorry, I haven't had much time to work on this, but I am open to PRs! :)

Also, thanks for the how-to!

**Comment by ingageco** [comment]
@unjust any chance you can put the code up so we can reference as an example?

**Comment by unjust** [comment]
Sure, feel free to look at the setup here
https://github.com/unjust/microradio_server/tree/master/server

**Comment by alfg** [comment]
Closing for now. Open to PRs if anyone wants to try this.
