### ISSUE TITLE
http play not working?

### ISSUE THREAD

**Issue by gerroon** [alfg/docker-nginx-rtmp#26]
HI

Thanks for the Docker image. I am able to play the OBS stream using RTMP but I cnat get the http ouytput to play in  VLC at all. I am using the exact same examples you gave except the IP adresses.  

I get playback in VLC but no visible video output. Maybe just outputs audio?

Can you please confirm that this actually works?

**Comment by aprisniak** [comment]
@gerroon I've just run this image on AWS EC2 t2.micro instance and configured OBS to stream on instance IP. And all works just fine.

**Comment by gerroon** [comment]
Hi

Thanks for the reply. I am closing the issue, because it is then my configureation here. Thanks for the awesome container.
