### ISSUE TITLE
[root@localhost ~]# docker run -it -p 1936:1935 -p 8080:80 --rm alfg/nginx-rtmp

### ISSUE THREAD

**Issue by nbutGit** [alfg/docker-nginx-rtmp#29]
[root@localhost ~]# docker run -it -p 1936:1935 -p 8080:80 --rm alfg/nginx-rtmp
2019/07/11 13:35:43 [notice] 1#1: using the "epoll" event method
2019/07/11 13:35:43 [notice] 1#1: nginx/1.16.0
2019/07/11 13:35:43 [notice] 1#1: built by gcc 6.4.0 (Alpine 6.4.0) 
2019/07/11 13:35:43 [notice] 1#1: OS: Linux 3.10.0-514.el7.x86_64
2019/07/11 13:35:43 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2019/07/11 13:35:43 [notice] 1#1: start worker processes
2019/07/11 13:35:43 [notice] 1#1: start worker process 6
2019/07/11 13:35:43 [notice] 1#1: start cache manager process 7
2019/07/11 13:35:43 [notice] 6#6: signal 28 (SIGWINCH) received
2019/07/11 13:35:43 [notice] 7#7: signal 28 (SIGWINCH) received
2019/07/11 13:35:43 [notice] 1#1: signal 28 (SIGWINCH) received
2019/07/11 13:35:43 [info] 6#6: epoll_wait() failed (4: Interrupted system call)
2019/07/11 13:35:43 [info] 7#7: epoll_wait() failed (4: Interrupted system call)
运行到这里就一直卡住了，请问这是什么问题呢

**Comment by alfg** [comment]
Hi @nbutGit, 

I'm not sure why this happens, but when I start docker for the first time it seems ok:
```
λ docker run -it -p 1936:1935 -p 8080:80 --rm alfg/nginx-rtmp
2019/07/12 04:08:15 [notice] 1#1: using the "epoll" event method
2019/07/12 04:08:15 [notice] 1#1: nginx/1.16.0
2019/07/12 04:08:15 [notice] 1#1: built by gcc 6.4.0 (Alpine 6.4.0)
2019/07/12 04:08:15 [notice] 1#1: OS: Linux 4.9.125-linuxkit
2019/07/12 04:08:15 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2019/07/12 04:08:15 [notice] 1#1: start worker processes
2019/07/12 04:08:15 [notice] 1#1: start worker process 6
2019/07/12 04:08:15 [notice] 1#1: start cache manager process 7
```

Then if I terminate the process, and start it again, I get the same issue as you:
```
λ docker run -it -p 1936:1935 -p 8080:80 --rm alfg/nginx-rtmp
2019/07/12 04:16:09 [notice] 1#1: using the "epoll" event method
2019/07/12 04:16:09 [notice] 1#1: nginx/1.16.0
2019/07/12 04:16:09 [notice] 1#1: built by gcc 6.4.0 (Alpine 6.4.0)
2019/07/12 04:16:09 [notice] 1#1: OS: Linux 4.9.125-linuxkit
2019/07/12 04:16:09 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2019/07/12 04:16:09 [notice] 1#1: start worker processes
2019/07/12 04:16:09 [notice] 1#1: start worker process 6
2019/07/12 04:16:09 [notice] 1#1: start cache manager process 7
2019/07/12 04:16:09 [notice] 1#1: signal 28 (SIGWINCH) received
2019/07/12 04:16:09 [notice] 6#6: signal 28 (SIGWINCH) received
2019/07/12 04:16:09 [info] 6#6: epoll_wait() failed (4: Interrupted system call)
2019/07/12 04:16:09 [notice] 7#7: signal 28 (SIGWINCH) received
2019/07/12 04:16:09 [info] 7#7: epoll_wait() failed (4: Interrupted system call)
```

The server still seems to be running, but not sure what's causing this. If I restart Docker, then error goes away.

**Comment by nbutGit** [comment]
@alfg Ok,thank you very much

**Comment by alfg** [comment]
I am also getting the same issue using the `nginx:alpine` image, outside of this project:

Using `nginx-test.conf`:
```
error_log /dev/stdout info;

events {
    worker_connections 1024;
}

http {
    access_log /dev/stdout combined;

    server {
        listen 80;
    }
}
```

Then running:
```
docker run -it -p 8080:80 --rm -v /path/to/nginx-test.conf:/etc/nginx/nginx.conf nginx:alpine

2019/07/12 04:49:30 [notice] 1#1: using the "epoll" event method
2019/07/12 04:49:30 [notice] 1#1: nginx/1.17.1
2019/07/12 04:49:30 [notice] 1#1: built by gcc 8.2.0 (Alpine 8.2.0)
2019/07/12 04:49:30 [notice] 1#1: OS: Linux 4.9.125-linuxkit
2019/07/12 04:49:30 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2019/07/12 04:49:30 [notice] 1#1: start worker processes
2019/07/12 04:49:30 [notice] 1#1: start worker process 6
2019/07/12 04:49:30 [notice] 1#1: signal 28 (SIGWINCH) received
2019/07/12 04:49:30 [notice] 6#6: signal 28 (SIGWINCH) received
2019/07/12 04:49:30 [info] 6#6: epoll_wait() failed (4: Interrupted system call)
```

Doesn't seem to be an issue affecting the project, but I see the same warnings.

**Comment by nbutGit** [comment]
@alfg It looks like nginx's problem.

**Comment by maddigibiter** [comment]
I'm still getting this regardless of new machine or after restarting docker

**Comment by HaFred** [comment]
> I'm still getting this regardless of new machine or after restarting docker

Hi, may I know did you solve it eventually?
