### ISSUE TITLE
Screen sizes

### ISSUE THREAD

**Issue by homanp** [alfg/docker-nginx-rtmp#3]
Hi @alfg!

You have some presets on sizes when serving the hls stream. Anyway those could be more dynamic.

How would one go about doing that?

Thanks!

**Comment by homanp** [comment]
I'll just fork this and try it with removing the `-s` flags in the nginx.conf

**Comment by alfg** [comment]
Hi @homanp. Yes, feel free to fork and adjust to your needs. :)

This project is mostly just a starter template with some presets. It's made to be forked and configured/customized.
