### ISSUE TITLE
Hardware acceleration support

### ISSUE THREAD

**Issue by kenosan** [alfg/docker-nginx-rtmp#30]
Any plans for hardware acceleration support using [libmfx](https://trac.ffmpeg.org/wiki/Hardware/QuickSync)?

**Comment by alfg** [comment]
Hi @kenosan, 

I have not considered this yet. Do you have any examples or benchmarks on how this can improve performance?

**Comment by kenosan** [comment]
I don't atm. I was hoping to give it a try and figured I would ask before. 

I’m using this image now and so far the lowest latency I can get when transcoding RTMP to HLS is a 10s delay during playback. I’m investigating how I can get that delay below 3 or 5 seconds. I’m curious what effect hardware acceleration might have. 

Some references:
https://trac.ffmpeg.org/wiki/HWAccelIntro
https://software.intel.com/en-us/blogs/2016/02/28/faster-media-apps-by-using-hw-acceleration

**Comment by alfg** [comment]
I see. I'm interested to see the effects of hardware acceleration as well. Have you tried adding libmfx to see if this improves your latency?

**Comment by kenosan** [comment]
I started but run into some compile issues. Will be spending some time on it and see how far I can get.

**Comment by alfg** [comment]
Closing for now. Feel free to re-open if you find more details if this should be added. Thanks!
