### ISSUE TITLE
Port 1935 pull

### ISSUE THREAD

**Issue by maddigibiter** [alfg/docker-nginx-rtmp#31]
Hi , 

I'm streaming rtmp from my host (ubuntu 18 on DO) and have this container running. Nginx on host is not listening to port 1935. I ran container using

`docker pull alfg/nginx-rtmp`

`docker run -it -p 1935:1935 -p 8080:80 --rm alfg/nginx-rtmp`

my container ip address is 

`docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' 3b1cabf80e89`

and result is: 

`172.17.0.2`

Obviously container ip differs from my server. Now question is, how would I be able to stream to 172.17.0.2:1935 ? 

I generate  rtmp://172.17.0.2:1935/live/stream using ffmpeg but container nginx is not listening to this port. If I listen on host nginx its all fine but docker isn't. 

 Is this correct or should I do rtmp://127.0.01:1935/live/stream from host or actual network ip? 

Thanks

**Comment by alfg** [comment]
Hi @maddigibiter, 

You should be able to stream to:
`rtmp://localhost:1935/stream/<key>`

and see the output to HLS via:
`http://localhost:8080/live/hello.m3u8`

The docker run command opens both `1935:1935` and `8080:80`. What happens when you try streaming to the rtmp endpoint?

**Comment by alfg** [comment]
Closing. Feel free to reopen or comment if you are still having this issue.
