### ISSUE TITLE
nginx not in PATH

### ISSUE THREAD

**Issue by CurtisLeeBolin** [alfg/docker-nginx-rtmp#35]
$ sudo docker run -ti --rm alfg/nginx-rtmp sh
/ # nginx -V
sh: nginx: not found

**Comment by alfg** [comment]
Yeah, it's not added to PATH since it's called directly from:
`/opt/nginx/sbin/nginx`

Do you need it in PATH?

**Comment by CurtisLeeBolin** [comment]
I was actually more curious about the prefixes being different which causes it to be out of PATH.
ffmpeg PREFIX=/usr/local
nginx --prefix=/opt/nginx

Why not both /usr/local ?
Is it just so the copy from is easier?

I do think it is better for it to be in PATH instead of having to search for it just to get some quick info like I was trying to do.  It would also be nice for the config files like fastcgi.conf, mime.types, ...  to be in the expected /etc/ location for easier volume/mount configuration.

**Comment by alfg** [comment]
All good points. I will look into updating this soon. Or a PR is also welcome. :)

**Comment by alfg** [comment]
Hey, I just added #36. Let me know if that works for you. Thanks!
