### ISSUE TITLE
Near real-time streaming (zero latency)

### ISSUE THREAD

**Issue by mnlbox** [alfg/docker-nginx-rtmp#39]
Hi @alfg,
First thanks for this repo :wink: 
I try to setup near real-time streaming based on this repo and OBS but I see near 12 seconds of delay in VLC. Have you any suggestions to decrease this delay? I need a lower than 2-second delay for my stream. Is it possible with RTMP at all?

**Comment by alfg** [comment]
Hi @mnlbox, 

This was discussed briefly on #34 by trying different configurations. I think the best we got was around 6 second delay. It might be difficult to obtain a near real-time (or under 2s) delay with HLS output. It could be a limitation on the source project, though: https://github.com/arut/nginx-rtmp-module.

I also saw this discussed on: https://github.com/video-dev/hls.js/issues/807

If you do figure this out, let us know. 😁

**Comment by mnlbox** [comment]
Hi @alfg,
Thanks for mention #34 
I'm also OK with 6 second delay but it's now near 12 second. How we can reduce this to 6 second without fork this repo and change `hls_fragment` and `hls_playlist_length`?

**Comment by alfg** [comment]
Without forking, you can try mounting and overriding `nginx.conf` with your localized copy and configuration with those options.

**Comment by mnlbox** [comment]
Oh, thanks, and what values you recommend for these two variables?

**Comment by alfg** [comment]
Maybe try `2s` and `6s` first and go from there. You can also try removing some of the  variants to reduce encoding time.

**Comment by alfg** [comment]
Closing for now. Let us know if you find a solution. :)
