### ISSUE TITLE
Work with latest-stable version of alpine instead of hardcoding a specific one?

### ISSUE THREAD

**Issue by reedog117** [alfg/docker-nginx-rtmp#42]
Is it possible to adapt this to work with the `latest-stable` branch of alpine instead of locking it to a particular version?

**Comment by alfg** [comment]
Hi @reedog117,

I lock Alpine to the last version I had this tested on. I don't like using `latest` since any updates to alpine upstream can break the build. 

However, since `3.8` is nearing EOL, I'll look into updating the latest working version soon.

**Comment by alfg** [comment]
Thanks @reedog117. I left some comments on your PR.

**Comment by alfg** [comment]
Fixed on #46 using 3.8. However, on your PR I would still like to have the forked source in a separate Dockerfile if possible.
