### ISSUE TITLE
included ffmpeg unable to restream to wowza

### ISSUE THREAD

**Issue by dromer** [alfg/docker-nginx-rtmp#44]
So, I'm trying to re-stream to a wowza rtmp server that utilizes authentication.
I tried both these forms:
```
-f flv "rtmp://[username:password@]server[:port][/app][/instance][/playpath]"
```
Which results in: ```Problem accessing the DNS. (addr: [username])```

And:
```
-f flv "rtmp://serveraddress[:port][/app][/streamname] flashver=FMLE/3.0\20(compatible;\20FMSc/1.0) live=true pubUser=myuser pubPasswd=mypassword"
```
Which does: ```RTMP_ReadPacket, failed to read RTMP packet header```

I see your ffmpeg build is missing a lot of flags, which is probably why this isn't working (?), perhaps lets expand it to include more capabilities?
```
ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 6.4.0 (Alpine 6.4.0)
  configuration: --prefix=/usr/local --enable-version3 --enable-gpl --enable-nonfree --enable-small --enable-libmp3lame --enable-libx264 --enable-libx265 --enable-libvpx --enable-libtheora --enable-libvorbis --enable-libopus --enable-libfdk-aac --enable-libass --enable-libwebp --enable-librtmp --enable-postproc --enable-avresample --enable-libfreetype --enable-openssl --disable-debug --disable-doc --disable-ffplay --extra-libs='-lpthread -lm'
```

As comparison my local ffmpeg:
```
ffmpeg version 4.1.5 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --disable-decoder=amrnb --disable-decoder=libopenjpeg --disable-libopencv --disable-outdev=sdl2 --disable-podpages --disable-sndio --disable-stripping --enable-libaom --enable-avfilter --enable-avresample --enable-gcrypt --disable-gnutls --enable-openssl --enable-gpl --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libfdk-aac --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libkvazaar --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libx265 --enable-libzimg --enable-libxvid --enable-libzvbi --enable-nonfree --enable-opencl --enable-opengl --enable-postproc --enable-pthreads --enable-shared --enable-version3 --enable-libwebp --incdir=/usr/include/x86_64-linux-gnu --libdir=/usr/lib/x86_64-linux-gnu --prefix=/usr --toolchain=hardened --enable-frei0r --enable-chromaprint --enable-libx264 --enable-libiec61883 --enable-libdc1394 --enable-vaapi --enable-libmfx --enable-libvmaf --disable-altivec --shlibdir=/usr/lib/x86_64-linux-gnu
```

(or I'm overlooking something, like some options not available on alpine?)

**Comment by dromer** [comment]
Interestingly the package from debian does not include ```--enable-librtmp``` even though it seems better and streaming rtmp o.O

I tried switching to ffmpeg ```4.1.5``` in the container to see if this was a regression, but it has the same issue. Will try to investigate further (looking at the different compile flags, but haven't found anything that I think could be related ..)

**Comment by dromer** [comment]
So, it seems indeed ```--enable-librtmp``` is the culprit here:

https://www.ffmpeg.org/ffmpeg-protocols.html#librtmp-rtmp_002c-rtmpe_002c-rtmps_002c-rtmpt_002c-rtmpte

Whereas the default rtmp implementation does support user:pass: 
https://www.ffmpeg.org/ffmpeg-protocols.html#rtmp


I now built the container with ```alpine:3.11```, ```FFMPEG_VERSION=4.2.2``` and no ```--enable-librtmp``` and get the result I want.

Can imagine you wanted librtmp to have all the extra fancy rtmp variants, but in my case I'd rather have a working authenticated re-stream going. ;)

Closing this issue for now.

**Comment by alfg** [comment]
Good find. I never considered this and realized there was a default rtmp implementation. Thanks for checking into this.

**Comment by dromer** [comment]
I actually ran into an old gstreamer post of mine where I had the same issue:
https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/issues/869

They ended up making their own implementation as well :P
https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/-/merge_requests/292
