### ISSUE TITLE
Getting HLS Watchers Count

### ISSUE THREAD

**Issue by victory7** [alfg/docker-nginx-rtmp#45]
Hi
Does anybody have any idea about getting HLS watchers count?
I tried this one and no chance!
https://github.com/faryon93/hlswatch
I know that it's a little difficult because it's a different thing from RTMP requests and we can't use rtmp-stat here.
But as I think you knew it's a very important part of a live streaming service and we couldn't ignore it at all.

Thanks in advance

**Comment by victory7** [comment]
Finally, I did this!
The good news is the application work as well as you expect.
https://github.com/faryon93/hlswatch

Unfortunately the documentation of that it's not well and I tried many times to get the result.
I used alfg/docker-nginx-rtmp image in one docker-compose.yml file and link them to each other.
We should use these lines in hls location in our nginx-rtmp nginx.conf file. Where the HLS requests are coming to.

nginx-rtmp => nginx.conf
`
location  / {
types {
        application/vnd.apple.mpegurl m3u8;
    }
    root /tmp;
    add_header Cache-Control no-cache;

     #To avoid issues with cross-domain HTTP requests (e.g. during development)
    add_header Access-Control-Allow-Origin *;

    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_pass http://hlswatch:80;
}
`

And in docker-compose file I have to services:
nginx-rtmp with this repo image (own build without any changes tagged stable)
faryon93/hlswatch
`
services:
  nginx-rtmp:
     image: alfg/nginx-rtmp:stable
     ports:
        - 1935:1935
        - 8081:80
     links:
        - hlswatch
  hlswatch:
    image: faryon93/hlswatch
`

Absolutely you should define your volumes depend on your application and configs.
Don't remember to change /stat location (I suppose you already added) to rtmpstat (or any other thing) to prevent conflict with hls stats.

After that, you serve hls requests to "/" and the hls watcher stats are in /stats !

I know it seems a little complicated but I guess if you are here probably know what I am talking about and you can change my settings to match your own app.

**Comment by alfg** [comment]
Thanks @victory7, this is a great reference to get this working!

**Comment by victory7** [comment]
Your Welcome @alfg, Thanks to you for your good repo.
