### ISSUE TITLE
passing environment variables to nginx

### ISSUE THREAD

**Issue by dromer** [alfg/docker-nginx-rtmp#48]
It would be nice to be able to pass env vars to the container that are used in the config.

There are several options for this:
* add perl module that can read env vars: https://medium.com/create-code/docker-environment-variables-and-nginx-93d7173f19ec
* use openresty as the base to do this with lua (openresty is awesome btw, just saying)
* <something else>

What do you think?

**Comment by dromer** [comment]
For now I "solved" it in my project by using a systemd service file to launch the service which does a ExecStartPre line that runs sed and creates the final nginx.conf from a template file (which I then mount inside the docker-nginx-rtmp instance).

**Comment by alfg** [comment]
Ah, yeah I do something similar on another project using `envsubt`:
https://github.com/alfg/docker-nginx-vod-module/blob/master/Dockerfile#L48

**Comment by alfg** [comment]
Also, the nginx docker repo also recommends `envsubt`:
https://hub.docker.com/_/nginx

If we do add this, are there any base environment variables to add to the `nginx.conf `template as a start? I'm not sure which should be configurable.

**Comment by dromer** [comment]
I don't think so.

Main thing would be to add ```bash``` to the image instead of just busybox I guess.

**Comment by absentio** [comment]
I use envsubst and it seems to work without problems.

**Comment by dromer** [comment]
I'm sure that it works, just that we don't have bash atm :)

**Comment by alfg** [comment]
Hey @dromer and @absentio, 

I added https://github.com/alfg/docker-nginx-rtmp/pull/50.

Thoughts?

**Comment by absentio** [comment]
@alfg  Great, that was what I exactly did to make it work on my local docker instance.

**Comment by dromer** [comment]
So, main difference would be that I have to mount the .template file instead and then pass the variables from the env?

Sounds ok to me.

**Comment by alfg** [comment]
Fixed on https://github.com/alfg/docker-nginx-rtmp/pull/50
