### ISSUE TITLE
Can't write files properly

### ISSUE THREAD

**Issue by absentio** [alfg/docker-nginx-rtmp#49]
Hi, just giving a try to this docker image. Got it working but when I try a simple directive like
`exec_pull echo "Hello" > /tmp/hello.txt`
it doesn't write the file when I pull the stream. 
If I run the same command on the shell then it works properly, i can even create files using touch.

Let me know how to fix. Thanks

**Comment by alfg** [comment]
Maybe a permissions thing? I got this when trying to run that `exec_pull` command:

```
nginx-rtmp_1  | 2020/03/14 21:10:23 [info] 6#6: exec: starting managed child 'echo'
nginx-rtmp_1  | 2020/03/14 21:10:24 [info] 6#6: exec: child 58 exited; ignoring
nginx-rtmp_1  | 2020/03/14 21:10:24 [info] 6#6: exec: terminating child 58
nginx-rtmp_1  | 2020/03/14 21:10:24 [notice] 6#6: signal 17 (SIGCHLD) received from 58
nginx-rtmp_1  | 2020/03/14 21:10:24 [notice] 6#6: unknown process 58 exited with code 0
nginx-rtmp_1  | 2020/03/14 21:10:24 [info] 6#6: epoll_wait() failed (4: Interrupted system call)
nginx-rtmp_1  | 2020/03/14 21:10:29 [info] 6#6: exec: starting managed child 'echo'
nginx-rtmp_1  | 2020/03/14 21:10:30 [info] 6#6: exec: child 59 exited; ignoring
nginx-rtmp_1  | 2020/03/14 21:10:30 [notice] 6#6: signal 17 (SIGCHLD) received from 59
nginx-rtmp_1  | 2020/03/14 21:10:30 [notice] 6#6: unknown process 59 exited with code 0
nginx-rtmp_1  | 2020/03/14 21:10:30 [info] 6#6: exec: terminating child 59
nginx-rtmp_1  | 2020/03/14 21:10:35 [info] 6#6: exec: starting managed child 'echo'
nginx-rtmp_1  | 2020/03/14 21:10:35 [info] 6#6: exec: child 60 exited; ignoring
nginx-rtmp_1  | 2020/03/14 21:10:35 [info] 6#6: exec: terminating child 60
nginx-rtmp_1  | 2020/03/14 21:10:35 [notice] 6#6: signal 17 (SIGCHLD) received from 60
nginx-rtmp_1  | 2020/03/14 21:10:35 [notice] 6#6: unknown process 60 exited with code 0
nginx-rtmp_1  | 2020/03/14 21:10:35 [info] 6#6: epoll_wait() failed (4: Interrupted system call)
nginx-rtmp_1  | 2020/03/14 21:10:40 [info] 6#6: exec: starting managed child 'echo'
nginx-rtmp_1  | 2020/03/14 21:10:41 [notice] 6#6: signal 17 (SIGCHLD) received from 61
nginx-rtmp_1  | 2020/03/14 21:10:41 [notice] 6#6: unknown process 61 exited with code 0
nginx-rtmp_1  | 2020/03/14 21:10:41 [info] 6#6: exec: child 61 exited; ignoring
nginx-rtmp_1  | 2020/03/14 21:10:41 [info] 6#6: exec: terminating child 61
nginx-rtmp_1  | 2020/03/14 21:10:46 [info] 6#6: exec: starting managed child 'echo'
```

**Comment by alfg** [comment]
Was this working before? I found a few issues that seem related:
https://github.com/arut/nginx-rtmp-module/issues/621
https://github.com/arut/nginx-rtmp-module/issues/886
https://github.com/arut/nginx-rtmp-module/issues/1335

**Comment by absentio** [comment]
It worked using another nginx-rtmp docker image, made by tiangolo. Anyway it seems it was only a problem with some kind of permission with touch or echo. If I exec an ffmpeg command it works.   I found i solution by using >> instead of > (it's kind of strange) and it worked (in append mode instead of write mode)

**Comment by alfg** [comment]
Oh strange. I wonder why it won't create the file then. I checked out the other image from tiangolo, but didn't see anything that stood out right away, except that it's using another base image.

I also tried another branch with creating a user and setting some permissions explicitly, but didn't seem to solve the issue there either.

**Comment by vitage** [comment]
The same issue ((

**Comment by shperrung** [comment]
Hi!
I'm new in this theme. Sorry for dump question but it it is unclear for me how to use this container.
`rtmp://<server ip>:1935/stream/$STREAM_NAME`
What is it path `/stream/$STREAM_NAME`?
I need to transcode stream in h265 into h264 with HW GPU and view final video stream in webOS. Can this container to do this and can you share with the example of command?

**Comment by alfg** [comment]
Closing for now. Feel free to re-open or comment if anyone else is still having this issue.
