### ISSUE TITLE
fdk-aac-dev missing when building Dockerfile

### ISSUE THREAD

**Issue by andreipopovici** [alfg/docker-nginx-rtmp#51]
https://github.com/alfg/docker-nginx-rtmp/blob/04ae94f9b54780d984a2e6529d8a8639d5a66082/Dockerfile#L85

It seems `fdk-aac-dev` has been moved from `testing` to `community` 🙏

**Comment by alfg** [comment]
Thanks @andreipopovici. This will be added as part of https://github.com/alfg/docker-nginx-rtmp/pull/50

**Comment by alfg** [comment]
Fixed on https://github.com/alfg/docker-nginx-rtmp/pull/50
