### ISSUE TITLE
volumes not mounting properly  - uncommenting SSL breaks docker

### ISSUE THREAD

**Issue by Supaiku** [alfg/docker-nginx-rtmp#59]
running 'exec -it DOCKER ID ls /opt/' reveals that the opt/certs volume was not properly mounted
Other volumes also do not mount properly

" [emerg] cannot load certificate " /opt/certs/example.com.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen(' /opt/certs/example.com.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
"

Ubuntu 18.04, fresh installation

UPDATE: It works with docker-compose up, but not when pre-built. Maybe I'm not using the build commands correctly or something is installed weird.

**Comment by alfg** [comment]
Can you post the docker command you are running? Are you passing the volume flags?

**Comment by alfg** [comment]
Closing. Feel free to re-open if you can provide an example of the issue.
