### ISSUE TITLE
docker-compose adds quotes to environment variables

### ISSUE THREAD

**Issue by dromer** [alfg/docker-nginx-rtmp#60]
This is an issue addressed in current master branch of docker-compose: https://github.com/docker/compose/issues/2854

Problem is that when you want to use environment variables you will see `' '` added to them which breaks the config if these are used in a path or such.

**Comment by alfg** [comment]
Is this still happening on the latest version of docker/docker-compose?

**Comment by alfg** [comment]
Closing for now. Feel free to re-open if anyone else is experiencing the same issue on the latest docker-compose.
