### ISSUE TITLE
Specific Docker Image tag beside latest 

### ISSUE THREAD

**Issue by schuleke** [alfg/docker-nginx-rtmp#62]
It would be nice to have an additional tag beside latest referring to a specific version, since using latest possibly breaks compatibility.

Are there any plans of creating version tags?

**Comment by alfg** [comment]
Hey @schuleke, sure I will add releases soon and push both `latest` and tags as part of the Docker image build.

**Comment by alfg** [comment]
Hi @schuleke, I've updated the Docker Hub config to build an image from releases/tags. I'll try to keep the releases and tags up to date after each major/minor release. Thanks for the idea!

https://github.com/alfg/docker-nginx-rtmp/releases
```
 docker pull alfg/nginx-rtmp:1.0
```
