### ISSUE TITLE
How do I inject my own nginx.conf into the image?

### ISSUE THREAD

**Issue by reedog117** [alfg/docker-nginx-rtmp#63]
I used to copy my own nginx.conf into the container after build - now that appears to be broken

**Comment by reedog117** [comment]
Better way to explain - why doesn't this work?

```Dockerfile
FROM alfg/nginx-rtmp

COPY nginx.conf /opt/nginx/nginx.conf
COPY nginx.conf /etc/nginx/nginx.conf
RUN apk --no-cache add curl

```

**Comment by reedog117** [comment]
Figured it out - had to copy to `/etc/nginx/nginx.conf.template`.

There needs to be a uniform, documented way of inserting an nginx.conf into the image. I think the method of injecting a custom `nginx.conf` has changed at least twice in the past year.

**Comment by alfg** [comment]
Yeah, it's `nginx.conf.template` to support passing in environment variables to the file. `envsubst` is run on the template file and outputted to `/etc/nginx/nginx.conf`. 

I updated `README.md` to make this more clear.
https://github.com/alfg/docker-nginx-rtmp/blob/master/README.md#custom-nginxconf

Thanks!
