### ISSUE TITLE
Example input streams

### ISSUE THREAD

**Issue by grebtsew** [alfg/docker-nginx-rtmp#65]
Hi,

Great project!

I'm quite new too ffmpeg an was wondering if you could add some example ffmpeg test input commands for window/linux in the README. 

I'm also wondering If you could help me with this issue.

I'm trying to make this command (stream screen in windows) work with the server following the README instructions, but the stream only works for ffmpeg/ffplay, not HLS, so I get the feeling I'm missing something:

`ffmpeg -f gdigrab -framerate 30 -video_size 1280x720 -i desktop -c:a libfdk_aac -b:a 128k -c:v libx264 -b:v 2500k -f flv rtmp://localhost:1935/stream/stream675`

I can read it with:
`ffplay rtmp://localhost:1935/stream/stream675`

On RTMP statics (http://localhost:8080/stat):
![bild](https://user-images.githubusercontent.com/8101164/80313360-c676e880-87ea-11ea-923d-54aa775cea02.png)

I'm using the latest image:
![bild](https://user-images.githubusercontent.com/8101164/80312863-fa044380-87e7-11ea-8970-db4be50a7d4d.png)

When I try to open: (http://localhost:8080/live/stream675.m3u8 in vlc) I get the following error:
![bild](https://user-images.githubusercontent.com/8101164/80312965-79921280-87e8-11ea-8068-38abcee4ffa0.png)

The videoJS example doesn't work either.

Any help appriciated!

Cheers,
@grebtsew

**Comment by alfg** [comment]
Hi @grebtsew, 

Can you try something like:
```
ffmpeg -f gdigrab -framerate 30 -i desktop -c:v libx264 -b:v 1600k -preset ultrafast -b 900k -c:a aac -b:a 128k -s 1920x1080 -x264opts keyint=50 -g 25 -pix_fmt yuv420p -f flv "rtmp://localhost:1935/stream/stream675"
```

Sometimes the HLS streams can take a second to generate, so they will 404 until you see them in the `hls` section on the stat page.

Also if you can verify you have `libfdk_aac` in your ffmpeg build. Curious why the audio doesn't seem to be receiving.

**Comment by grebtsew** [comment]
Your command works perfectly! Awesome! Many thanks!

I can receive the .m3u8 format in VideoJS and VLC. Nginx/stat now looks like this:
![bild](https://user-images.githubusercontent.com/8101164/80318301-82dfa700-8809-11ea-8237-91d9a11bb49e.png)

Regarding `libfdk_aac ` it appears I'm missing it. I do not need audio at this point. But might be useful later. I just installed the latest stable x64 windows ffmpeg see -buildconf below. Any hints? 
`
ffmpeg version git-2020-04-24-a501947 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.3.1 (GCC) 20200328
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 42.102 / 56. 42.102
  libavcodec     58. 81.100 / 58. 81.100
  libavformat    58. 42.101 / 58. 42.101
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 79.100 /  7. 79.100
  libswscale      5.  6.101 /  5.  6.101
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100

  configuration:
    --enable-gpl
    --enable-version3
    --enable-sdl2
    --enable-fontconfig
    --enable-gnutls
    --enable-iconv
    --enable-libass
    --enable-libdav1d
    --enable-libbluray
    --enable-libfreetype
    --enable-libmp3lame
    --enable-libopencore-amrnb
    --enable-libopencore-amrwb
    --enable-libopenjpeg
    --enable-libopus
    --enable-libshine
    --enable-libsnappy
    --enable-libsoxr
    --enable-libsrt
    --enable-libtheora
    --enable-libtwolame
    --enable-libvpx
    --enable-libwavpack
    --enable-libwebp
    --enable-libx264
    --enable-libx265
    --enable-libxml2
    --enable-libzimg
    --enable-lzma
    --enable-zlib
    --enable-gmp
    --enable-libvidstab
    --enable-libvmaf
    --enable-libvorbis
    --enable-libvo-amrwbenc
    --enable-libmysofa
    --enable-libspeex
    --enable-libxvid
    --enable-libaom
    --disable-w32threads
    --enable-libmfx
    --enable-ffnvcodec
    --enable-cuda-llvm
    --enable-cuvid
    --enable-d3d11va
    --enable-nvenc
    --enable-nvdec
    --enable-dxva2
    --enable-avisynth
    --enable-libopenmpt
    --enable-amf
`

@grebtsew

**Comment by alfg** [comment]
Ah, yeah if you are installing a compiled version of ffmpeg from their website, it may be missing a bunch of options. You would have to compile and include these options from source, or use a compiled build that already has the options built in. 

See: https://trac.ffmpeg.org/wiki/CompilationGuide

Or check out my Docker FFmpeg repo, which has `libfdk-aac` enabled:
https://github.com/alfg/docker-ffmpeg
