### ISSUE TITLE
Multiple errors when installing with docker run

### ISSUE THREAD

**Issue by djdynamix** [alfg/docker-nginx-rtmp#66]
Installing the image with "docker run" gets as far as "start cache manager process 11" then throws multiple errors, including "Client sent HTTP/1.1 request without "Host" header while reading client request headers", and "Client closed keepalive connection". It never completes, and eventually freezes completely after about 1hr. The "Tiangolo" image installs perfectly, but lacks the SSL configuration which I need.

My Docker is a "virgin install" with no other containers, and is installed on a CentOS 7 VPS alongside a CPanel/Apache LAMP stack.

**Comment by alfg** [comment]
> My Docker is a "virgin install" with no other containers, and is installed on a CentOS 7 VPS alongside a CPanel/Apache LAMP stack.

Hi @djdynamix, does this happen when you run locally too?

**Comment by alfg** [comment]
Hmm, ok. Can you post your docker run command or docker-compose setup?

**Comment by djdynamix** [comment]
I'm afraid I don't have that docker installation any more. As of yesterday, I've moved my testing to its own dedicated VPS, after a nail-biting night when experiments with Node.JS streaming brought 12 websites and two Icecast streams down for an hour! Thanks for your help. If I get any further information, I'll let you know.

**Comment by alfg** [comment]
OK, closing for now. Feel free to re-open if there's any further information on how reproduce the issue.
