### ISSUE TITLE
Error activating SSL

### ISSUE THREAD

**Issue by canal6hn** [alfg/docker-nginx-rtmp#67]
Greetings, after activating the lines in nginx.conf I change the 2 files in the certs folder obtaining them from sslforfree.com then in hub.docker.com I create the docker but when I start it it presents the following error:

nginx: [emerg] cannot load certificate "/opt/certs/live.canal6.hn.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/opt/certs/live.canal6.hn.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)

![Screenshot_1](https://user-images.githubusercontent.com/64667960/81749634-3632d780-9469-11ea-910b-e5c354a1c4a8.jpg)

**Comment by alfg** [comment]
Hi @canal6hn, 

Are you mounting the volumes containing the certs? Do you have a docker or docker-compose command you can share?

**Comment by alfg** [comment]
Closing. Feel free to re-open if you can provide the info above.
