### ISSUE TITLE
Getting the server to record the stream

### ISSUE THREAD

**Issue by tanja84dk** [alfg/docker-nginx-rtmp#68]
I would like to know if there is a way to get the server to record the rtmp stream

**Comment by alfg** [comment]
hi @tanja84dk,

Check out the recording directives on:
https://github.com/arut/nginx-rtmp-module/wiki/Directives#record
https://github.com/arut/nginx-rtmp-module/wiki/Control-module

Unfortunately I haven't tried or have any examples that I can provide, but it might be best to check their issues tracker for info.
