### ISSUE TITLE
Using nginx-rtmp to mirror source stream on multiple instances

### ISSUE THREAD

**Issue by rhummelmose** [alfg/docker-nginx-rtmp#69]
Hi alfg,

Thanks for the work you've done, your image works great!

In a k8s cluster I'm setting up one container with your default options that will receive the stream and make it available on HTTP interrnally in the clusterr. I then setup N containers that are supposed to exec_pull from the first container, copying the streams and making it available on HTTP externally. The reason being that I want it to be horizontally scalable, supporting in theory an unlimited number of viewers.

However, I'm having an issue getting it to work as it seems like accessing the http server doesn't start the application that will generate the hls files.

I've pushed my work here: https://github.com/rhummelmose/nginx-rtmp-hls-mirror/blob/master/nginx.conf

And here are the k8s manifests: https://github.com/rhummelmose/duah-k8s-gitops

I hope that you have an idea for how I can resolve this :)

Best,
Rasmus

**Comment by rhummelmose** [comment]
Update:

This could be my problem: https://github.com/arut/nginx-rtmp-module/wiki/FAQ#i-use-pull-directive-to-get-stream-from-remote-location-that-works-for-rtmp-clients-but-does-not-work-for-hls

**Comment by alfg** [comment]
Hi @rhummelmose, 

Sounds like a great setup. Unfortunately, I don't have much experience using `exec_pull` in this case, but sounds like it could be related to the wiki FAQ you linked. There's also another open issue where a simple `exec_pull echo` doesn't seem to work either:
https://github.com/alfg/docker-nginx-rtmp/issues/49

Maybe related?

**Comment by rhummelmose** [comment]
Works now using exec_static as advised in the FAQ from nginx and as can be seen here:
https://github.com/rhummelmose/nginx-rtmp-hls-mirror/blob/master/nginx.conf#L14

Thanks @alfg again 👍

**Comment by alfg** [comment]
Awesome, that's good to know! Thanks for reporting back. 

OK to close this issue?

**Comment by rhummelmose** [comment]
Yes, now closed :)
