### ISSUE TITLE
how to create VIDEO based on file .mp4

### ISSUE THREAD

**Issue by aodytj** [alfg/docker-nginx-rtmp#73]
how to create VIDEO based on file .mp4
how to config nginx

**Comment by alfg** [comment]
Hi @aodytj, 

It is possible to stream from an MP4 file. However, I don't have an example nginx config to show. Check out the wiki on:
https://github.com/arut/nginx-rtmp-module/wiki/Directives#video-on-demand

**Comment by alfg** [comment]
Closing. Feel free to reply if any other questions. Thanks!
