### ISSUE TITLE
Python video

### ISSUE THREAD

**Issue by Georgepop** [alfg/docker-nginx-rtmp#77]
How can I send python video to server and how to watch it ?
thank you !

**Comment by alfg** [comment]
Hey @Georgepop, 

Can you clarify sending a python video to a server?

If you're trying to stream an MP4, you can use the directive specified in the `nginx-rtmp` repo:
https://github.com/arut/nginx-rtmp-module/wiki/Directives#video-on-demand

And you play the video as described in the readme:
https://github.com/alfg/docker-nginx-rtmp#watch-stream

**Comment by Georgepop** [comment]
thank you !
