### ISSUE TITLE
Why do you use the '-fflags nobuffer' option in the documentation?

### ISSUE THREAD

**Issue by hongyi-zhao** [alfg/docker-nginx-rtmp#79]
[Here](https://github.com/alfg/docker-nginx-rtmp#watch-stream), you told the following method for watching the stream:

`FFplay: ffplay -fflags nobuffer rtmp://localhost:1935/stream/hello`

I still can't figure out why you use the `-fflags nobuffer` option. Any hints will be highly appreciated.

Regards,
HY

**Comment by alfg** [comment]
It's an option to help reduce the stream latency. 

See: 
https://trac.ffmpeg.org/wiki/StreamingGuide#Latency
https://ffmpeg.org/ffplay-all.html#toc-Format-Options
> ‘nobuffer’
> Reduce the latency introduced by buffering during initial input streams analysis. 

In the readme, it's used just for reference to test playback.

**Comment by hongyi-zhao** [comment]
Thanks. I like to check the options of ffmpeg as following:
```
$ ffmpeg -h full |& grep nobuffer
     nobuffer                     .D......... reduce the latency introduced by optional buffering
```
