### ISSUE TITLE
Discussion on some additional feature enhancement: rtmps and access control of publish/subscribe.

### ISSUE THREAD

**Issue by hongyi-zhao** [alfg/docker-nginx-rtmp#80]
For stream publish/subscribe through `docker-nginx-rtmp` container, I want to add/implement the following features:

1. The `rtmps` protocol support.
2. The access control, say, based on username/password.

Any hints will be highly appreciated.

Regards,
HY

**Comment by alfg** [comment]
Hey @hongyi-zhao, 

1) I don't think rtmps is supported by [nginx-rtmp](https://github.com/arut/nginx-rtmp-module/issues/457), but there are some guides posted in that thread on how to set it up via stunnel.

https://github.com/alfg/docker-nginx-rtmp/issues/25

2) What type of access control are you looking into? Any more detail or an example you can provide?
You can also check out the notify directives to make use of authentication:
https://github.com/arut/nginx-rtmp-module/wiki/Directives#notify

**Comment by hongyi-zhao** [comment]
> What type of access control are you looking into? Any more detail or an example you can provide?

To be frank, I'm really a green hand on livestreaming. From my current understanding, when it comes to it access control, I mean something like the following : 
 
Constrain the publishing source of the stream, say, using the username/password pair.
Constrain the playback of the stream, say, using the username/password pair when the user accesses the stream URLs.

**Comment by alfg** [comment]
My experience is limited on this part, but from my understanding you can authenticate the user to your own API using the `on_publish` or `on_connect` directive from the Notify docs I linked. You can pass query parameters as part of the stream key:

For example, if you are connecting via:
```
rtmp://localhost:1935/stream/hello?key=foobar123
```

You can use the query parameter as a key.

In your `nginx.conf`, you can define something like this using `on_connect` or `on_publish`, which will send a request to that URL when the user attempts to connect:
```
rtmp {
    server {
        listen 1935;
        chunk_size 4000;

        application stream {
            live on;

            allow publish all;
            deny publish all;
            on_publish http://api.example.tv/auth;
            notify_method get;

            exec ffmpeg -i rtmp://localhost:1935/stream/$name
              -c:a libfdk_aac -b:a 128k -c:v libx264 -b:v 2500k -f flv -g 60 -r 60 -filter:v scale=1920:-1 -preset superfast -profile:v baseline rtmp://localhost:1935/hls/$name_1080p2628kbs;
       }
    }
}
```

Then on your backend API, you can write an auth handler for `http://api.example.tv/auth` that can validate the name and key, then respond with a 403 or 200 accordingly.

**Comment by hongyi-zhao** [comment]
Thanks for your notes, I also find another example given [here](https://github.com/phily245/streamer#authentication).

**Comment by alfg** [comment]
Sounds good. Can this be closed?
