### ISSUE TITLE
Feature request: mpeg dash stream support.

### ISSUE THREAD

**Issue by hongyi-zhao** [alfg/docker-nginx-rtmp#81]
Currently, HLS and dash are the most popular two stream formats. Could you please add support for dash in this project?

Regards,
HY

**Comment by alfg** [comment]
Sure. I'll check into this and add to the nginx.conf.

**Comment by alfg** [comment]
`nginx-rtmp` doesn't seem to support multiple variants for DASH:
https://github.com/arut/nginx-rtmp-module/wiki/Directives#mpeg-dash

So to keep things simple, I'll just leave it as HLS support only.

If nginx-rtmp adds support for multiple bitrates for dash, then I'll add it in, but might be unlikely as the nginx-rtmp project doesn't seem to be maintained as much anymore.

**Comment by hongyi-zhao** [comment]
I've been told that some fork of nginx-rtmp-module is more actively been maintained, but I can’t remember the username for that fork at the moment.

**Comment by alfg** [comment]
Ya, I am aware of the forks. However, this Docker build is based on the origin.
