### ISSUE TITLE
Some enhancements/improvements used by me in my Dockerfile.

### ISSUE THREAD

**Issue by hongyi-zhao** [alfg/docker-nginx-rtmp#82]
1. Use curl instead of wget for downloading in Dockerfile. IMHO, curl is more powerful and versatile than wget, especially in richness of protocol support and performance of download. As we all know, git is built on top of libcurl to implement its own transfer functionality. Take into account all the above, I've switched to curl for all downloading jobs included in my [Dockerfile](https://github.com/hongyi-zhao/docker-nginx-rtmp/blob/master/Dockerfile).  See relative lines in my Dockerfile, e.g., [here](https://github.com/hongyi-zhao/docker-nginx-rtmp/blob/8b79d6cc8040cdb13cfe1e6f0be1f8b9fabf5436/Dockerfile#L80) for more detailed info. 

2. Pass the core number to make in buiding time with something like `--build-arg MAKEFLAGS="-j$(nproc)"` instead of assigning a fixed core number for make in Dockerfile as this: `ARG MAKEFLAGS="-j4"`. See my notes in my [Dockerfile](https://github.com/hongyi-zhao/docker-nginx-rtmp/blob/8b79d6cc8040cdb13cfe1e6f0be1f8b9fabf5436/Dockerfile#L5) for more detailed info.

**Comment by alfg** [comment]
Hi @hongyi-zhao, 

Possible to add this via PR?

**Comment by hongyi-zhao** [comment]
If you like, I would give a try.

**Comment by alfg** [comment]
Give it a shot. :)

**Comment by hongyi-zhao** [comment]
In my Dockerfile, I've added many notes which don't appropriated for PR, so I would make a clean branch for making the PR.

**Comment by alfg** [comment]
Yeah, as long as it follows along with the same conventions I have in place, it should be fine. You can replace wget with curl, and add the build flag for nproc.

**Comment by hongyi-zhao** [comment]
I've a habit that adding a lot of comments mainly as memo for myself when I'm not familiar with something at the initial stage of learning some knowledge & skills.

**Comment by hongyi-zhao** [comment]
Dear @alfg, after the issue was posted, I've found the [srs project](https://github.com/ossrs/srs). It seems that it's very powerful and also dead easy to use with its [docker images](https://github.com/ossrs/srs-docker). The author also supplies a concise instruction [here](https://medium.com/@winlinvip/srs-build-live-video-streaming-by-only-3-steps-55411fc9b524). So, I suggest you give an eye on it. Based on the existence of such a powerful and open source streaming media solution, I think we should not waste our time recreating the wheels for similar work.

Regards,
HY

**Comment by alfg** [comment]
Hey @hongyi-zhao, 

Thanks for the heads up. I'm aware of the project, and there's many other implementations of RTMP too. But as I mentioned before, this project here is just a Docker template for `nginx-rtmp` module in it's current state.
