### ISSUE TITLE
Feature request: hls.js and video.js integration templates.

### ISSUE THREAD

**Issue by hongyi-zhao** [alfg/docker-nginx-rtmp#83]
As we've discussed before, I still think that it would be worthwhile to add the integration templates for [hls.js](https://github.com/video-dev/hls.js) and [video.js](https://github.com/videojs/video.js) in this project.

**Comment by alfg** [comment]
hls.js demo player is now added:
https://github.com/alfg/docker-nginx-rtmp/blob/master/static/player.html
