### ISSUE TITLE
Why do you use two sets of cloud based building settings?

### ISSUE THREAD

**Issue by hongyi-zhao** [alfg/docker-nginx-rtmp#84]
Why do you use [.github/workflows](https://github.com/alfg/docker-nginx-rtmp/tree/master/.github/workflows) and [.travis.yml](https://github.com/alfg/docker-nginx-rtmp/blob/master/.travis.yml) at the same time?

Regards,
HY

**Comment by alfg** [comment]
I was setting it up to push to Github Registry before it was in general availability. I ran into limitations, but I will pick it back up again eventually.
