### ISSUE TITLE
nginx.conf with Docker volume

### ISSUE THREAD

**Issue by Maverick1983** [alfg/docker-nginx-rtmp#9]
It would be possible to change the path of the nginx.conf file so that you could map the volume for local configuration

**Comment by alfg** [comment]
Hi @Maverick1983, 

Where would you recommend updating the nginx.conf path to?

If you map a volume to `/opt/nginx/nginx.conf`, would that replace the added default `nginx.conf` with your local configuration?

**Comment by Maverick1983** [comment]
Hi,

If I map a volume to /opt/nginx/nginx.conf the nginx server does not work
because it does not find the installation of it in / opt / nginx

2018-04-08 7:41 GMT+02:00 Alfred Gutierrez <notifications@github.com>:

**Comment by alfg** [comment]
Sorry for the late response. Too bad that didn't work. I would suggest just forking and customizing the `nginx.conf` to your needs. 

If you happen to get the nginx.conf mapped as a volume, I would be happy to add to the instructions in the README.

**Comment by andrewc2** [comment]
Hey so I came up with a solution for this, while not perfect, is definitely an option.

I created the container normally then once everything settled and I could see the text nginx page, I copied the /opt/nginx/ directory to the location I wanted it on my root server using `docker cp`

So in this case it looked like this `docker cp container-name:/opt/nginx/ /home/username/nginx`

Then I just reran the container with the volume mapped `-v /home/user/nginx/:/opt/nginx/`

**Comment by mikeydiamonds** [comment]
Loving your container @alfg. Just in case anyone runs into the issue of customizing nginx.conf you can just mount a volume:
`docker run -it -p 1935:1935 -p 8080:80 -v /host/path/to/nginx.conf.template:/etc/nginx/nginx.conf.template --rm alfg/nginx-rtmp`

Due to https://github.com/alfg/docker-nginx-rtmp/pull/50 you have to mount over `nginx.conf.template`
