### ISSUE TITLE
Merging multiple input (streams) and filtering to output

### ISSUE THREAD

**Issue by bundyfx** [alfg/docker-nginx-rtmp#90]
Hello!

Just a quick question, is it possible to merge two incoming streams and output them as one (with filtering applied)?

Im thinking something like this ->

![Screenshot 2021-02-22 at 12 35 32](https://user-images.githubusercontent.com/12060844/108703162-89fb4280-750a-11eb-9419-3b60139f2b3b.png)

However - I am not understanding how this works as `http://localhost:8080/player.html?url=http://localhost:8080/live/output_480p1128kbs` (for example) gives a 404..

**Comment by alfg** [comment]
Hey @bundyfx, 

It sounds like it may be possible if ffmpeg supports it, but I haven't tried myself. I'm not sure how nginx-rtmp will handle the $stream name, though. Let us know if you get this working. :)

Also, can you try using `http://localhost:8080/player.html?url=http://localhost:8080/live/output.m3u8`?

**Comment by alfg** [comment]
Closing for now. Feel free to re-open or reply if you have an update. Thanks.

**Comment by looped-monk** [comment]
> Hello!
> 
> Just a quick question, is it possible to merge two incoming streams and output them as one (with filtering applied)?
> 
> Im thinking something like this ->
> 
> ![Screenshot 2021-02-22 at 12 35 32](https://user-images.githubusercontent.com/12060844/108703162-89fb4280-750a-11eb-9419-3b60139f2b3b.png)
> 
> However - I am not understanding how this works as `http://localhost:8080/player.html?url=http://localhost:8080/live/output_480p1128kbs` (for example) gives a 404..

Hello, 
saw your post and i have posted a similar question in issues here

https://github.com/alfg/docker-nginx-rtmp/issues/183
