### ISSUE TITLE
"host not found in url" when pushing to another stream service

### ISSUE THREAD

**Issue by bennyevangelista** [alfg/docker-nginx-rtmp#93]
I'm trying to setup the rtmp server to push stream to external stream service (youtube, facebook, twitch...), this is supported by the nginx rtmp module with the "push" directive:

```
...
  application stream {
            live on;
	    push rtmp://live.twitch.tv/app/xxxxxxx.....; 
            exec ffmpeg -i ....
  }
```
but I'm getting the error

`nginx: [emerg] host not found in url "live.twitch.tv/app/xxxxxx....." in /etc/nginx/nginx.conf:16`

this seems to affect only the docker version of nginx-rtmp, I'm struggling with it from weeks with no success, do you have any info?

**Comment by alfg** [comment]
Could be a networking issue. Can you access `live.twitch.tv` from within your container? 

Seems similar to this issue: https://github.com/arut/nginx-rtmp-module/issues/766

**Comment by bennyevangelista** [comment]
I've had already checked that bug, still without solution. 
I believe that is something related to DNS resolution, but I can't figure what. If i remove the push directive the container correctly starts and it is able to reach the domain (tested with ping and curl from the container), but it seems that it cannot resolve dns at startup, causing nginx to crash.
I'll try to contact rtmp-module devs.

**Comment by bennyevangelista** [comment]
I finally found that was something related to the network driver provided by QNAP (I'm using docker on a NAS), which allows me to set an IP (DHCP or static) to the container. Starting the container attached to a bridge network works correctly.
Thank you very much for the support 👍

**Comment by alfg** [comment]
Awesome. Glad you got it figured out. Thanks for reporting back with an update. :)
