### ISSUE TITLE
stub_status

### ISSUE THREAD

**Issue by fcecagno** [alfg/docker-nginx-rtmp#99]
Would you consider generating the docker images with the nginx compilation flag `--with-http_stub_status_module`? This way it would be possible to export connection metrics from nginx. Thanks!

**Comment by alfg** [comment]
Hey @fcecagno, 

Sorry for the late response. I can add this flag into the next build soon. Thanks for the suggestion.

**Comment by PAOK1926** [comment]
did you finally added this?
